### ISSUE TITLE
continues 404 in logs

### ISSUE THREAD

**Issue by ohadlevy** [t0mer/HAvid-19#2]
docker-compose up
```
Recreating botvid-19 ... done
Attaching to botvid-19
botvid-19    | 2020-09-13 08:36:09.855 | INFO     | __main__:<module>:49 - I am listening...
botvid-19    | Traceback (most recent call last):
botvid-19    |   File "/usr/local/lib/python3.8/site-packages/telepot/loop.py", line 58, in run_forever
botvid-19    |     result = self._bot.getUpdates(offset=offset,
botvid-19    |   File "/usr/local/lib/python3.8/site-packages/telepot/__init__.py", line 1000, in getUpdates
botvid-19    |     return self._api_request('getUpdates', _rectify(p))
botvid-19    |   File "/usr/local/lib/python3.8/site-packages/telepot/__init__.py", line 491, in _api_request
botvid-19    |     return api.request((self._token, method, params, files), **kwargs)
botvid-19    |   File "/usr/local/lib/python3.8/site-packages/telepot/api.py", line 155, in request
botvid-19    |     return _parse(r)
botvid-19    |   File "/usr/local/lib/python3.8/site-packages/telepot/api.py", line 150, in _parse
botvid-19    |     raise exception.TelegramError(description, error_code, data)
botvid-19    | telepot.exception.TelegramError: ('Not Found', 404, {'ok': False, 'error_code': 404, 'description': 'Not Found'})
```

this continues in a loop, and the service is not starting.

my docker-compose file is
```
version: "3.7"
services:
 
  botvid-19:
    image: techblog/botvid-19
    container_name: botvid-19
    restart: always
    labels:
      - "com.ouroboros.enable=true"
    environment:
      - USER_ID=<>
      - USER_KEY=<>
    ports:
      - "6700:6700"
```
