### ISSUE TITLE
how to use this repo with HA?

### ISSUE THREAD

**Issue by ohadlevy** [t0mer/HAvid-19#3]
is there an integration project with HA ? or reference configuration? thanks!

**Comment by dmatik** [comment]
Please see below:

```
rest_command:

  sign_havid:
    url: "http://{{ip}}:{{port}}/edu/sign" 
    method: "GET"
    timeout: 60
```

```
shell_command:

  download_havid: "curl http://{{ip}}:{{port}}/edu/statement -o /config/www/havid.jpg"
```

```
script:

  sign_havid:
    alias: Sign HAvid-19
    sequence:
        - service: rest_command.sign_havid
          data:
            ip: !secret synology_zeg_host
            port: !secret havid_port

  download_havid:
    alias: Download HAvid-19
    sequence:
        - service: shell_command.download_havid
          data:
            ip: !secret synology_zeg_host
            port: !secret havid_port

  sign_and_download_havid:
    alias: Sign and Download HAvid-19
    sequence:
        - service: script.sign_havid
        - delay:
            seconds: 30
        - service: script.download_havid
        - service: notify.dimatelegram
          data:
            title: 'Health Declaration'
            message: 'Signed'
            data:
              photo:
                - file: /config/www/havid.jpg
                  caption: "Health Declaration"
```
